version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:2.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack_data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
